// SATBot — SPaG Question Sets (multiple years)
// Original questions in the style of KS2 SATs SPaG Paper 1

const SPAG_SETS = [
  {
    year: "2024",
    questions: [
      {id:1,marks:1,topic:"Word classes",q:"Which word is a verb in this sentence?\n\n\"The excited children rushed into the classroom.\"",type:"mcq",options:["excited","children","rushed","classroom"],answer:"rushed",explanation:"A verb is a doing or being word. 'Rushed' is the action the children performed. 'Excited' is an adjective; 'children' and 'classroom' are nouns."},
      {id:2,marks:1,topic:"Punctuation",q:"Which sentence uses a semi-colon correctly?",type:"mcq",options:["It was cold outside; she put on her coat.","It was cold; outside she put on her coat.","It was; cold outside she put on her coat.","It was cold outside she; put on her coat."],answer:"It was cold outside; she put on her coat.",explanation:"A semi-colon joins two independent clauses of equal weight. Both 'It was cold outside' and 'she put on her coat' are complete sentences — they are closely related and balanced in importance."},
      {id:3,marks:1,topic:"Sentence types",q:"Which sentence is a command?",type:"mcq",options:["The dog is barking.","Is the dog barking?","Stop that dog from barking!","What a noise that dog is making!"],answer:"Stop that dog from barking!",explanation:"A command gives an instruction or order. It starts with a verb ('Stop'). Note: exclamations start with 'What' or 'How'. The example 'What a noise...' is an exclamation, not a command."},
      {id:4,marks:1,topic:"Conjunctions",q:"Which conjunction shows cause in this sentence?\n\n\"She missed the bus _______ she overslept.\"",type:"mcq",options:["although","because","but","whereas"],answer:"because",explanation:"'Because' introduces a reason or cause — she missed the bus as a result of oversleeping. 'Although' and 'but' show contrast; 'whereas' shows comparison."},
      {id:5,marks:1,topic:"Punctuation",q:"Which sentence punctuates a fronted adverbial correctly?",type:"mcq",options:["Slowly and carefully, she opened the door.","Slowly and carefully she, opened the door.","Slowly, and carefully she opened the door.","Slowly and carefully she opened, the door."],answer:"Slowly and carefully, she opened the door.",explanation:"A fronted adverbial is a phrase at the start of a sentence that tells us how, when, or where. It must be followed by a comma before the main clause begins."},
      {id:6,marks:1,topic:"Verb forms",q:"Which sentence is written in the present perfect tense?",type:"mcq",options:["She painted the fence.","She is painting the fence.","She has painted the fence.","She will paint the fence."],answer:"She has painted the fence.",explanation:"Present perfect = has/have + past participle ('has painted'). It describes an action completed at an unspecified time before now. Option A = simple past; B = present progressive; D = future simple."},
      {id:7,marks:1,topic:"Punctuation",q:"Which sentence uses a dash correctly to add extra information?",type:"mcq",options:["The winner — Jamie — received a gold trophy.","The winner Jamie — received a gold trophy.","The winner — Jamie received a gold trophy.","The — winner Jamie received a gold trophy."],answer:"The winner — Jamie — received a gold trophy.",explanation:"Dashes can be used in pairs to add parenthetical information (like brackets). Both dashes must be present: before and after 'Jamie'."},
      {id:8,marks:1,topic:"Word classes",q:"What is the grammatical term for the underlined word?\n\n\"She walked across the bridge.\"  (across)",type:"mcq",options:["Conjunction","Preposition","Adverb","Adjective"],answer:"Preposition",explanation:"A preposition shows the relationship between a noun/pronoun and another word, often indicating place, direction or time. 'Across' shows the direction of her movement in relation to 'the bridge'."},
      {id:9,marks:1,topic:"Spelling",q:"Choose the correct spelling:",type:"mcq",options:["necesary","neccesary","necessary","necessery"],answer:"necessary",explanation:"'Necessary' — one collar (c) and two socks (ss): n-e-c-e-s-s-a-r-y. A useful memory trick: it has one C and two S letters."},
      {id:10,marks:1,topic:"Punctuation",q:"Tick the sentence that correctly punctuates direct speech.",type:"mcq",options:["\"I love football\" said Marcus.","\"I love football,\" said Marcus.","\"I love football\", said Marcus.","\"I love football.\" said Marcus."],answer:"\"I love football,\" said Marcus.",explanation:"When the reporting clause follows speech, use a comma (not a full stop) inside the closing speech mark. The correct form: \"I love football,\" said Marcus."},
      {id:11,marks:1,topic:"Clauses",q:"Which sentence contains an embedded relative clause?",type:"mcq",options:["The cat, which was black, sat on the mat.","The cat sat on the mat and it was black.","The black cat sat on the mat.","The cat sat on the mat although it was black."],answer:"The cat, which was black, sat on the mat.",explanation:"A relative clause beginning with 'which', 'who' or 'that' is embedded (inserted) within the main clause using commas. 'which was black' is embedded between commas."},
      {id:12,marks:1,topic:"Word classes",q:"Which word is an abstract noun?",type:"mcq",options:["table","happiness","quickly","jump"],answer:"happiness",explanation:"An abstract noun names something you cannot physically touch or see — a concept, feeling, or idea. 'Happiness' is a feeling. 'Table' = concrete noun; 'quickly' = adverb; 'jump' = verb."},
      {id:13,marks:1,topic:"Punctuation",q:"Which sentence correctly uses a colon to introduce a list?",type:"mcq",options:["She packed: her coat, boots and umbrella.","She packed her coat: boots and umbrella.","She packed her coat, boots: and umbrella.","She: packed her coat, boots and umbrella."],answer:"She packed: her coat, boots and umbrella.",explanation:"A colon introduces a list after a complete clause. 'She packed' is a complete clause — the colon then introduces what she packed. A colon should not interrupt the flow of the main clause."},
      {id:14,marks:1,topic:"Sentence structure",q:"Which sentence is an example of an exclamation?",type:"mcq",options:["Run as fast as you can!","What a brilliant performance that was!","Stop making so much noise!","Did you enjoy the show?"],answer:"What a brilliant performance that was!",explanation:"A grammatical exclamation must begin with 'What' or 'How', contain a subject and verb, and end with an exclamation mark. Only option B meets all criteria."},
      {id:15,marks:1,topic:"Word classes",q:"What is the word class of 'joyfully' in this sentence?\n\n\"The children joyfully accepted the gift.\"",type:"mcq",options:["Adjective","Adverb","Noun","Verb"],answer:"Adverb",explanation:"'Joyfully' is an adverb — it modifies the verb 'accepted', telling us HOW the children accepted the gift. Most adverbs of manner end in '-ly'."},
      {id:16,marks:1,topic:"Punctuation",q:"Where does the apostrophe go in this phrase?\n\nThe womens changing room",type:"mcq",options:["women's changing room","womens' changing room","womens changing room'","women'S changing room"],answer:"women's changing room",explanation:"'Women' is an irregular plural (doesn't end in -s). For irregular plurals, add apostrophe + s: women's. Compare 'girls' (regular plural) → girls' changing room."},
      {id:17,marks:1,topic:"Vocabulary",q:"Which word is an antonym of 'generous'?",type:"mcq",options:["kind","charitable","mean","giving"],answer:"mean",explanation:"An antonym is a word with the opposite meaning. 'Generous' means willing to give freely. 'Mean' means unwilling to share or give — the opposite. 'Kind' and 'charitable' are synonyms."},
      {id:18,marks:1,topic:"Tense",q:"Rewrite this sentence in the passive voice:\n\n\"The gardener planted the flowers.\"",type:"short",answer:"The flowers were planted by the gardener.",explanation:"Passive voice: the object ('the flowers') becomes the subject. Use 'to be' + past participle: 'were planted'. The original agent becomes a 'by' phrase: 'by the gardener'."},
      {id:19,marks:1,topic:"Punctuation",q:"Which option correctly uses brackets for parenthesis?",type:"mcq",options:["The Eiffel Tower (built in 1889) is in Paris.","The Eiffel Tower built (in 1889) is in Paris.","The (Eiffel Tower built in 1889) is in Paris.","The Eiffel Tower built in (1889 is in Paris.)"],answer:"The Eiffel Tower (built in 1889) is in Paris.",explanation:"Brackets add extra, non-essential information to a sentence. The information inside must be removable without changing the core meaning. 'built in 1889' is the extra detail here."},
      {id:20,marks:1,topic:"Formal/informal",q:"Which sentence uses the subjunctive mood correctly?",type:"mcq",options:["If I was you, I would apologise.","If I were you, I would apologise.","If I am you, I would apologise.","If I be you, I would apologise."],answer:"If I were you, I would apologise.",explanation:"The subjunctive mood is used for hypothetical or contrary-to-fact conditions. 'If I were you' (not 'was') is the correct subjunctive form — it expresses an imaginary condition."}
    ]
  },
  {
    year: "2023",
    questions: [
      {id:1,marks:1,topic:"Word classes",q:"Which word in this sentence is a pronoun?\n\n\"They left their bags by the door.\"",type:"mcq",options:["They","left","bags","door"],answer:"They",explanation:"A pronoun stands in place of a noun. 'They' replaces the name of a group of people. 'Left' is a verb; 'bags' and 'door' are nouns."},
      {id:2,marks:1,topic:"Punctuation",q:"Which sentence uses hyphens correctly to create a compound adjective?",type:"mcq",options:["She wore a well-known dress.","She wore a well known dress.","She wore a wellknown dress.","She wore a well, known dress."],answer:"She wore a well-known dress.",explanation:"Compound adjectives used before a noun are hyphenated: well-known. Without the hyphen, 'well' could be read as a separate adverb. If used after the noun, no hyphen is needed (e.g. 'The dress was well known')."},
      {id:3,marks:1,topic:"Sentence types",q:"Which sentence is a statement?",type:"mcq",options:["Put your pen down.","Have you finished your work?","I have finished my work.","What a long piece of work that was!"],answer:"I have finished my work.",explanation:"A statement gives information and ends with a full stop. Option A is a command; B is a question; D is an exclamation."},
      {id:4,marks:1,topic:"Conjunctions",q:"Which subordinating conjunction best completes this sentence?\n\n\"He continued to play _______ he was injured.\"",type:"mcq",options:["because","so","even though","therefore"],answer:"even though",explanation:"'Even though' introduces a concessive clause — the action continued despite the obstacle (the injury). 'Because' shows cause; 'so' shows result; 'therefore' is a connective, not a conjunction."},
      {id:5,marks:1,topic:"Punctuation",q:"Which sentence uses commas correctly in a list?",type:"mcq",options:["She bought apples, pears, bananas, and grapes.","She bought apples pears, bananas and grapes.","She bought, apples, pears, bananas and grapes.","She bought apples, pears bananas and grapes."],answer:"She bought apples, pears, bananas, and grapes.",explanation:"Commas separate items in a list. Each item is followed by a comma (the final comma before 'and' is called an Oxford comma — accepted in KS2). No comma before the first item."},
      {id:6,marks:1,topic:"Verb forms",q:"Which sentence uses the future perfect tense?",type:"mcq",options:["She will sing tomorrow.","She is singing now.","She has sung already.","She will have sung by noon."],answer:"She will have sung by noon.",explanation:"Future perfect = will have + past participle ('will have sung'). It describes an action that will be completed before a specific future time. Option A = future simple; C = present perfect."},
      {id:7,marks:1,topic:"Punctuation",q:"Which sentence uses an ellipsis correctly?",type:"mcq",options:["She opened the door and... screamed.","She opened... the door and screamed.","...She opened the door and screamed.","She opened the door and screamed..."],answer:"She opened the door and... screamed.",explanation:"An ellipsis (...) can create dramatic pause or suspense within a sentence. Placing it before the climax ('screamed') builds tension effectively."},
      {id:8,marks:1,topic:"Word classes",q:"Which sentence contains a modal verb?",type:"mcq",options:["She runs every morning.","She could run faster than anyone.","She ran a marathon last year.","She is running in the race."],answer:"She could run faster than anyone.",explanation:"Modal verbs express possibility, ability, permission or obligation: can, could, may, might, shall, should, will, would, must. 'Could' is a modal verb indicating ability."},
      {id:9,marks:1,topic:"Spelling",q:"Choose the correct spelling:",type:"mcq",options:["recieve","recievve","receive","receeve"],answer:"receive",explanation:"'Receive' follows the rule 'i before e except after c': r-e-c-e-i-v-e. After the letter 'c', use 'ei' not 'ie'."},
      {id:10,marks:1,topic:"Punctuation",q:"Which is the correct punctuation for this sentence?\n\n\"Weve been waiting for an hour said Priya\"",type:"mcq",options:["\"We've been waiting for an hour,\" said Priya.","\"Weve been waiting for an hour,\" said Priya.","\"We've been waiting for an hour\" said Priya.","\"We've been waiting for an hour.\" said Priya."],answer:"\"We've been waiting for an hour,\" said Priya.",explanation:"The apostrophe in 'We've' (contraction of 'we have') is essential. The comma goes inside the closing speech mark. The reporting clause 'said Priya' starts with a lower-case letter."},
      {id:11,marks:1,topic:"Clauses",q:"Which part of this sentence is the subordinate clause?\n\n\"Although the rain was heavy, they finished the match.\"",type:"mcq",options:["Although the rain was heavy","they finished the match","the rain was heavy","Although"],answer:"Although the rain was heavy",explanation:"A subordinate clause cannot stand alone as a sentence — it depends on the main clause for meaning. 'Although the rain was heavy' makes incomplete sense on its own."},
      {id:12,marks:1,topic:"Word classes",q:"Which sentence contains a determiner?",type:"mcq",options:["She runs fast.","The dog barked loudly.","He shouted angrily.","They left quickly."],answer:"The dog barked loudly.",explanation:"A determiner comes before a noun to introduce it: the, a, an, this, that, these, those, my, his, her, some, any. 'The' is a determiner before 'dog'."},
      {id:13,marks:1,topic:"Punctuation",q:"Which sentence uses inverted commas correctly for a title?",type:"mcq",options:["She read 'The Midnight Fox' in one evening.","She read the Midnight Fox in one evening.","She read \"the Midnight Fox\" in one evening.","She read The Midnight Fox in one evening."],answer:"She read 'The Midnight Fox' in one evening.",explanation:"Titles of books, films or works are placed in inverted commas (single or double). The title words are capitalised."},
      {id:14,marks:1,topic:"Sentence structure",q:"Which sentence uses a fronted adverbial?",type:"mcq",options:["She quietly tiptoed down the stairs.","Down the stairs, she quietly tiptoed.","She tiptoed quietly down the stairs.","She tiptoed down the stairs quietly."],answer:"Down the stairs, she quietly tiptoed.",explanation:"A fronted adverbial is an adverbial phrase placed at the front of the sentence, followed by a comma. 'Down the stairs,' is the fronted adverbial here."},
      {id:15,marks:1,topic:"Word classes",q:"Identify the preposition in this sentence:\n\n\"The letter was hidden beneath the floorboard.\"",type:"mcq",options:["hidden","beneath","floorboard","letter"],answer:"beneath",explanation:"'Beneath' is a preposition showing the position of the letter in relation to the floorboard. It indicates place/position."},
      {id:16,marks:1,topic:"Punctuation",q:"Which sentence uses an apostrophe for omission correctly?",type:"mcq",options:["I ca'nt believe it's raining again.","I can't believe its raining again.","I can't believe it's raining again.","I cant believe it's raining again."],answer:"I can't believe it's raining again.",explanation:"'Can't' = cannot (apostrophe replaces 'no'). 'It's' = it is (apostrophe replaces 'i'). Both contractions need apostrophes. 'Its' without apostrophe is possessive (e.g. the dog wagged its tail)."},
      {id:17,marks:1,topic:"Vocabulary",q:"Which word is a synonym for 'abundant'?",type:"mcq",options:["scarce","plentiful","empty","rare"],answer:"plentiful",explanation:"'Abundant' means existing in large quantities. 'Plentiful' is its synonym. 'Scarce', 'rare' and 'empty' all suggest the opposite — small or no quantity."},
      {id:18,marks:1,topic:"Tense",q:"Rewrite this sentence using the passive voice:\n\n\"The wind blew down the old oak tree.\"",type:"short",answer:"The old oak tree was blown down by the wind.",explanation:"Passive: object ('the old oak tree') becomes subject. Use 'to be' + past participle: 'was blown down'. Agent: 'by the wind'. Note: past tense of 'blow' = 'blown' (irregular verb)."},
      {id:19,marks:1,topic:"Punctuation",q:"Which option is punctuated correctly?",type:"mcq",options:["My three favourite subjects are: maths, science and English.","My three favourite subjects are maths science and English.","My three favourite: subjects are maths, science and English.","My three favourite subjects are; maths, science and English."],answer:"My three favourite subjects are: maths, science and English.",explanation:"A colon after a complete clause introduces a list. 'My three favourite subjects are' is a complete clause — the colon then introduces the list."},
      {id:20,marks:1,topic:"Formal/informal",q:"Which sentence is in the most formal register?",type:"mcq",options:["Thanks for getting back to me so quick!","Cheers for the speedy reply!","I am grateful for your prompt response.","Got your message — cheers!"],answer:"I am grateful for your prompt response.",explanation:"Formal register uses complete sentences, standard vocabulary and no contractions or colloquialisms. Option C uses formal vocabulary ('grateful', 'prompt response') and no informal language."}
    ]
  },
  {
    year: "2022",
    questions: [
      {id:1,marks:1,topic:"Word classes",q:"Which word is an adjective in this sentence?\n\n\"The enormous wave crashed against the rocky cliff.\"",type:"mcq",options:["crashed","enormous","against","cliff"],answer:"enormous",explanation:"An adjective describes a noun. 'Enormous' describes the wave. 'Crashed' is a verb; 'against' is a preposition; 'cliff' is a noun. (Note: 'rocky' is also an adjective but is not listed as an option.)"},
      {id:2,marks:1,topic:"Punctuation",q:"Which sentence uses a colon correctly?",type:"mcq",options:["He had one goal: to win the championship.","He had: one goal to win the championship.","He had one: goal to win the championship.","He: had one goal to win the championship."],answer:"He had one goal: to win the championship.",explanation:"A colon follows a complete main clause and introduces an explanation or elaboration. 'He had one goal' is a complete clause; the colon then reveals what that goal was."},
      {id:3,marks:1,topic:"Sentence types",q:"Which is an example of a rhetorical question?",type:"mcq",options:["What time does the film start?","Have you tidied your room?","Who could forget that glorious summer?","Where did you put my keys?"],answer:"Who could forget that glorious summer?",explanation:"A rhetorical question is asked for effect — no answer is expected. 'Who could forget that glorious summer?' implies everyone remembers it and is used for emphasis, not to seek information."},
      {id:4,marks:1,topic:"Conjunctions",q:"Choose the correct coordinating conjunction:\n\n\"She wanted to stay up late _______ her parents said no.\"",type:"mcq",options:["because","although","but","since"],answer:"but",explanation:"Coordinating conjunctions join two equally weighted clauses (FANBOYS: for, and, nor, but, or, yet, so). 'But' shows contrast here. 'Because', 'although' and 'since' are subordinating conjunctions."},
      {id:5,marks:1,topic:"Punctuation",q:"Which sentence uses commas correctly around a relative clause?",type:"mcq",options:["The book which I borrowed, was fascinating.","The book, which I borrowed, was fascinating.","The book, which I borrowed was fascinating.","The book which, I borrowed, was fascinating."],answer:"The book, which I borrowed, was fascinating.",explanation:"A non-defining relative clause (extra information not essential to the meaning) is enclosed in commas. 'Which I borrowed' is non-defining — it adds detail but removing it leaves the core meaning intact."},
      {id:6,marks:1,topic:"Verb forms",q:"Which sentence is written in the past progressive tense?",type:"mcq",options:["She sang beautifully.","She has sung the song.","She was singing when the phone rang.","She sings every day."],answer:"She was singing when the phone rang.",explanation:"Past progressive = was/were + present participle (-ing form). It describes an ongoing action in the past, often interrupted by another event ('when the phone rang')."},
      {id:7,marks:1,topic:"Punctuation",q:"Which sentence uses parenthetical commas correctly?",type:"mcq",options:["My teacher, Mrs Green is very kind.","My teacher Mrs Green, is very kind.","My teacher, Mrs Green, is very kind.","My, teacher Mrs Green, is very kind."],answer:"My teacher, Mrs Green, is very kind.",explanation:"Parenthetical commas come in pairs to enclose non-essential information. 'Mrs Green' is extra identifying information — it can be removed without changing the main meaning ('My teacher is very kind')."},
      {id:8,marks:1,topic:"Word classes",q:"Which sentence uses an adverbial phrase of time?",type:"mcq",options:["She ran quickly down the road.","She ran every morning before school.","She ran to the park.","She ran because she was late."],answer:"She ran every morning before school.",explanation:"'Every morning before school' is an adverbial phrase of time — it tells us WHEN she ran. Option A = manner; C = place; D = reason (subordinate clause)."},
      {id:9,marks:1,topic:"Spelling",q:"Choose the correct spelling:",type:"mcq",options:["accomodation","accommodation","accomadation","acomodation"],answer:"accommodation",explanation:"'Accommodation' has double c and double m: a-c-c-o-m-m-o-d-a-t-i-o-n. Memory tip: it has enough room for 2 cots and 2 mattresses (double c, double m)!"},
      {id:10,marks:1,topic:"Punctuation",q:"Which sentence is correctly punctuated?",type:"mcq",options:["\"Don't touch that!\" she warned.","\"Don't touch that\" she warned.","\"Don't touch that!\" She warned.","\"don't touch that!\" she warned."],answer:"\"Don't touch that!\" she warned.",explanation:"After an exclamation mark inside speech marks, the reporting clause ('she warned') starts with a lower case letter. The first word of speech is capitalised."},
      {id:11,marks:1,topic:"Clauses",q:"How many clauses does this sentence contain?\n\n\"Although it was cold, I went for a walk because I needed fresh air.\"",type:"mcq",options:["One","Two","Three","Four"],answer:"Three",explanation:"Clause 1: 'Although it was cold' (subordinate); Clause 2: 'I went for a walk' (main); Clause 3: 'because I needed fresh air' (subordinate). Three clauses total."},
      {id:12,marks:1,topic:"Word classes",q:"Which word is a conjunction in this sentence?\n\n\"She was tired yet she kept working.\"",type:"mcq",options:["tired","yet","working","kept"],answer:"yet",explanation:"'Yet' here is a coordinating conjunction meaning 'but' or 'nevertheless', joining two contrasting clauses. It can also be an adverb of time ('not yet'), but here it functions as a conjunction."},
      {id:13,marks:1,topic:"Punctuation",q:"Which sentence uses a question mark correctly?",type:"mcq",options:["I wonder if it will rain tomorrow?","She asked whether I had finished?","Can you help me with this problem?","He wanted to know what time it was?"],answer:"Can you help me with this problem?",explanation:"Only direct questions need a question mark. 'Can you help me' is a direct question addressed to someone. The other options are indirect questions (reported speech/thoughts) — these don't need question marks."},
      {id:14,marks:1,topic:"Sentence structure",q:"Which technique does this sentence use?\n\n\"Not only did she win the race, but she also broke the record.\"",type:"mcq",options:["Passive voice","Fronted adverbial","Inverted sentence structure","Relative clause"],answer:"Inverted sentence structure",explanation:"Starting with 'Not only' creates an inverted structure — the auxiliary verb 'did' comes before the subject 'she'. This is a deliberate stylistic choice for emphasis."},
      {id:15,marks:1,topic:"Word classes",q:"Which word is a possessive pronoun in this sentence?\n\n\"The red bag is mine.\"",type:"mcq",options:["red","bag","is","mine"],answer:"mine",explanation:"Possessive pronouns show ownership without needing a noun after them: mine, yours, his, hers, its, ours, theirs. 'Mine' replaces 'my bag'. Compare possessive adjectives (my, your, his) which come before a noun."},
      {id:16,marks:1,topic:"Punctuation",q:"Which option shows the correct use of an apostrophe in a plural possessive?",type:"mcq",options:["The teachers' staff room was repainted.","The teacher's' staff room was repainted.","The teachers's staff room was repainted.","The teachers staff room was repainted."],answer:"The teachers' staff room was repainted.",explanation:"For regular plurals ending in -s, add only an apostrophe after the -s: teachers'. This shows that many teachers share the staff room."},
      {id:17,marks:1,topic:"Vocabulary",q:"Which word is closest in meaning to 'transparent'?",type:"mcq",options:["dark","clear","solid","rough"],answer:"clear",explanation:"'Transparent' means see-through or easy to see through. 'Clear' is the closest synonym (e.g. clear glass). 'Dark' and 'solid' are opposites; 'rough' refers to texture."},
      {id:18,marks:1,topic:"Tense",q:"Rewrite this sentence in the simple future tense:\n\n\"She was reading the report.\"",type:"short",answer:"She will read the report.",explanation:"Simple future = will + base form of verb. 'Was reading' (past progressive) → 'will read' (future simple). Do not write 'will be reading' — that is the future progressive tense."},
      {id:19,marks:1,topic:"Punctuation",q:"Which sentence uses a semi-colon correctly to separate items in a complex list?",type:"mcq",options:["We visited Paris, France; Rome, Italy; and Berlin, Germany.","We visited Paris, France, Rome, Italy, and Berlin, Germany.","We visited: Paris, France; Rome, Italy; and Berlin, Germany.","We visited Paris; France, Rome; Italy, and Berlin; Germany."],answer:"We visited Paris, France; Rome, Italy; and Berlin, Germany.",explanation:"Semi-colons can separate items in a list when the items themselves contain commas. This avoids confusion — each destination (city + country) is kept together."},
      {id:20,marks:1,topic:"Formal/informal",q:"Rewrite this informal sentence in formal English:\n\n\"Kids nowadays don't wanna read books.\"",type:"short",answer:"Children today do not wish to read books.",explanation:"Formal English: replace 'Kids' with 'Children', 'nowadays' with 'today', expand 'don't' to 'do not', and replace informal 'wanna' with 'wish to'. Avoid slang and contractions."}
    ]
  },
  {
    year: "2019",
    questions: [
      {id:1,marks:1,topic:"Word classes",q:"Which word is a noun in this sentence?\n\n\"The fierce wind rattled the windows.\"",type:"mcq",options:["fierce","wind","rattled","windows"],answer:"wind",explanation:"'Wind' is a noun — it names a thing. 'Windows' is also a noun but is not listed. 'Fierce' is an adjective; 'rattled' is a verb."},
      {id:2,marks:1,topic:"Punctuation",q:"Which sentence uses an apostrophe correctly?",type:"mcq",options:["Its going to rain today.","It's going to rain today.","It's going to rain to'day.","Its' going to rain today."],answer:"It's going to rain today.",explanation:"'It's' is the contraction of 'it is'. The apostrophe replaces the letter 'i'. 'Its' without apostrophe is the possessive pronoun (e.g. the cat licked its paw)."},
      {id:3,marks:1,topic:"Sentence types",q:"What punctuation mark should end this sentence?\n\n\"What a fantastic goal that was\"",type:"mcq",options:["Full stop (.)","Question mark (?)","Exclamation mark (!)","Comma (,)"],answer:"Exclamation mark (!)",explanation:"This is an exclamation — it starts with 'What' and contains a subject ('that') and verb ('was'). Exclamations end with an exclamation mark."},
      {id:4,marks:1,topic:"Conjunctions",q:"Which sentence uses a subordinating conjunction correctly?",type:"mcq",options:["She cried and laughed at the same time.","She laughed, but she was crying inside.","She laughed until the tears rolled down her face.","She laughed or cried — she wasn't sure which."],answer:"She laughed until the tears rolled down her face.",explanation:"'Until' is a subordinating conjunction that introduces a subordinate clause of time. 'And' and 'but' and 'or' are coordinating conjunctions joining equal clauses."},
      {id:5,marks:1,topic:"Punctuation",q:"Which sentence uses a colon correctly to introduce an explanation?",type:"mcq",options:["There was only one problem: the key had snapped in the lock.","There was: only one problem the key had snapped in the lock.","There was only: one problem the key had snapped in the lock.","There was only one problem the key: had snapped in the lock."],answer:"There was only one problem: the key had snapped in the lock.",explanation:"A colon after a complete clause introduces an explanation. 'There was only one problem' is the complete main clause; the colon then reveals what that problem was."},
      {id:6,marks:1,topic:"Verb forms",q:"Which sentence uses a modal verb to express obligation?",type:"mcq",options:["She can swim very well.","She might go to the party.","She must complete the form today.","She will arrive tomorrow."],answer:"She must complete the form today.",explanation:"'Must' expresses strong obligation or necessity — there is no choice. 'Can' = ability; 'might' = possibility; 'will' = future certainty."},
      {id:7,marks:1,topic:"Punctuation",q:"Which sentence uses bullet points correctly?",type:"mcq",options:["The rules are:\n• No running\n• No shouting\n• No eating in class","The rules are\n• No running.\n• No shouting.\n• No eating in class.","The rules, are:\n• No running\n• No shouting\n• No eating in class","The rules are:\n• no running\n• no shouting\n• no eating in class"],answer:"The rules are:\n• No running\n• No shouting\n• No eating in class",explanation:"A colon introduces the list. Each bullet point starts with a capital letter (when they are short phrases). No full stops are needed at the end of short bullet-point phrases."},
      {id:8,marks:1,topic:"Word classes",q:"Which word is used as an adverb in this sentence?\n\n\"She sang so beautifully that everyone cried.\"",type:"mcq",options:["sang","so","beautifully","cried"],answer:"beautifully",explanation:"'Beautifully' is an adverb modifying the verb 'sang' (telling us HOW she sang). 'So' is also an adverb here (modifying 'beautifully') but 'beautifully' is the primary adverb answer expected."},
      {id:9,marks:1,topic:"Spelling",q:"Choose the correct spelling:",type:"mcq",options:["concious","consciuous","conscious","consciuos"],answer:"conscious",explanation:"'Conscious' is spelled: c-o-n-s-c-i-o-u-s. Note the 'sc' in the middle and the ending '-ious'. Related word: conscience."},
      {id:10,marks:1,topic:"Punctuation",q:"Which sentence uses capital letters correctly?",type:"mcq",options:["my favourite subject is english and maths.","My favourite subject is English and Maths.","My favourite subject is english and maths.","my Favourite Subject is English and Maths."],answer:"My favourite subject is English and Maths.",explanation:"Capital letters are needed at the start of sentences and for proper nouns. 'English' and 'Maths' are subject names and are capitalised. Common nouns and adjectives like 'favourite' and 'subject' do not get capitals mid-sentence."},
      {id:11,marks:1,topic:"Clauses",q:"Which type of clause is underlined?\n\n\"She read the letter that had arrived that morning.\"  (that had arrived that morning)",type:"mcq",options:["Main clause","Subordinate adverbial clause","Relative clause","Coordinate clause"],answer:"Relative clause",explanation:"'That had arrived that morning' begins with the relative pronoun 'that' and gives more information about 'the letter'. This makes it a relative clause."},
      {id:12,marks:1,topic:"Word classes",q:"Which sentence contains a proper noun?",type:"mcq",options:["The city is very busy.","London is a very busy city.","The capital city is very busy.","Every city has busy streets."],answer:"London is a very busy city.",explanation:"A proper noun is the specific name of a person, place or thing — it always starts with a capital letter. 'London' is a proper noun. 'City', 'capital' and 'streets' are common nouns."},
      {id:13,marks:1,topic:"Punctuation",q:"Add the correct punctuation to complete this sentence:\n\n\"Oh no _____ I've left my bag on the bus___\"",type:"mcq",options:["Oh no, I've left my bag on the bus!","Oh no! I've left my bag on the bus.","Oh no! I've left my bag on the bus!","Oh no. I've left my bag on the bus!"],answer:"Oh no! I've left my bag on the bus!",explanation:"'Oh no!' is an interjection expressing alarm — it needs an exclamation mark. The second sentence also conveys strong feeling/urgency, so an exclamation mark fits. Both exclamation marks are acceptable."},
      {id:14,marks:1,topic:"Sentence structure",q:"Which sentence uses a conditional clause?",type:"mcq",options:["She went to school despite the rain.","If she studies hard, she will pass the exam.","She studied hard and passed the exam.","She passed the exam because she had studied hard."],answer:"If she studies hard, she will pass the exam.",explanation:"A conditional clause (often beginning with 'if' or 'unless') describes a condition and its consequence. 'If she studies hard' is the condition; 'she will pass' is the result."},
      {id:15,marks:1,topic:"Word classes",q:"What type of word is 'however' in this sentence?\n\n\"She wanted to go; however, it was too late.\"",type:"mcq",options:["Conjunction","Adverb","Preposition","Determiner"],answer:"Adverb",explanation:"'However' is a conjunctive adverb — it connects two ideas (like a conjunction) but functions grammatically as an adverb. It is preceded by a semi-colon and followed by a comma."},
      {id:16,marks:1,topic:"Punctuation",q:"Which sentence correctly uses an apostrophe with a singular proper noun?",type:"mcq",options:["James' book was on the shelf.","James's book was on the shelf.","Jamess book was on the shelf.","Jame's book was on the shelf."],answer:"James's book was on the shelf.",explanation:"For singular nouns ending in -s, add apostrophe + s: James's. Both 'James's' and 'James'' are accepted in English, but in KS2 SATs, 'James's' is the preferred form."},
      {id:17,marks:1,topic:"Vocabulary",q:"Which word is a synonym for 'timid'?",type:"mcq",options:["bold","shy","brave","noisy"],answer:"shy",explanation:"'Timid' means lacking confidence or easily frightened. 'Shy' is its closest synonym. 'Bold' and 'brave' are antonyms; 'noisy' is unrelated to character confidence."},
      {id:18,marks:1,topic:"Tense",q:"Rewrite this sentence in the present perfect tense:\n\n\"She visited Paris three times.\"",type:"short",answer:"She has visited Paris three times.",explanation:"Present perfect = has/have + past participle. 'Visited' (simple past) → 'has visited' (present perfect). This implies she has been there before and the relevance to the present is implied."},
      {id:19,marks:1,topic:"Punctuation",q:"Which sentence is correctly punctuated?",type:"mcq",options:["The shop which opened last year sells fresh bread, cakes and coffee.","The shop, which opened last year, sells fresh bread, cakes and coffee.","The shop which opened last year, sells fresh bread cakes and coffee.","The shop which, opened last year, sells fresh bread, cakes and coffee."],answer:"The shop, which opened last year, sells fresh bread, cakes and coffee.",explanation:"The relative clause 'which opened last year' is non-defining — it adds extra information but is not essential. It must be enclosed in commas. The list also uses commas correctly."},
      {id:20,marks:1,topic:"Formal/informal",q:"Which sentence is written in an impersonal, formal style?",type:"mcq",options:["You should eat more fruit and veg.","It is recommended that people increase their consumption of fruit and vegetables.","Eat more fruit and veg — it's good for you!","Everyone should eat their five a day."],answer:"It is recommended that people increase their consumption of fruit and vegetables.",explanation:"Formal, impersonal writing uses the passive voice ('It is recommended'), avoids direct address ('you'), uses full vocabulary ('consumption', 'vegetables') and no contractions or colloquialisms."}
    ]
  },
  {
    year: "2018",
    questions: [
      {id:1,marks:1,topic:"Word classes",q:"Which word is an adverb in this sentence?\n\n\"The dog barked loudly outside the door.\"",type:"mcq",options:["dog","loudly","outside","door"],answer:"loudly",explanation:"'Loudly' is an adverb modifying the verb 'barked' — it tells us HOW the dog barked. 'Outside' here is a preposition; 'dog' and 'door' are nouns."},
      {id:2,marks:1,topic:"Punctuation",q:"Which sentence uses apostrophes correctly?",type:"mcq",options:["The boys' football rolled into the neighbour's garden.","The boy's football rolled into the neighbours' garden.","The boys football rolled into the neighbours's garden.","The boys' football rolled into the neighbours garden."],answer:"The boys' football rolled into the neighbour's garden.",explanation:"'Boys'' — the football belongs to more than one boy (plural possessive); add apostrophe after -s. 'Neighbour's' — one neighbour (singular possessive); add apostrophe + s."},
      {id:3,marks:1,topic:"Sentence types",q:"What type of sentence is this?\n\n\"Please sit down and open your books.\"",type:"mcq",options:["Statement","Question","Command","Exclamation"],answer:"Command",explanation:"A command gives an instruction. It begins with a verb ('Please sit'). 'Please' makes it polite but it is still a command (imperative sentence)."},
      {id:4,marks:1,topic:"Conjunctions",q:"Which word is a coordinating conjunction?",type:"mcq",options:["although","while","yet","unless"],answer:"yet",explanation:"Coordinating conjunctions join clauses or phrases of equal weight (FANBOYS: for, and, nor, but, or, yet, so). 'Yet' is a coordinating conjunction. 'Although', 'while' and 'unless' are subordinating conjunctions."},
      {id:5,marks:1,topic:"Punctuation",q:"Which sentence correctly uses a semi-colon?",type:"mcq",options:["She loves art; her sister prefers music.","She loves art her; sister prefers music.","She loves; art her sister prefers music.","She loves art her sister; prefers music."],answer:"She loves art; her sister prefers music.",explanation:"A semi-colon joins two independent but closely related clauses. 'She loves art' and 'her sister prefers music' are both complete sentences connected by their contrast."},
      {id:6,marks:1,topic:"Verb forms",q:"Which sentence contains a verb in the subjunctive mood?",type:"mcq",options:["I suggest that she goes first.","I suggest that she go first.","I suggest that she going first.","I suggest that she will go first."],answer:"I suggest that she go first.",explanation:"The subjunctive uses the base form of the verb (without 's' for third person). 'She go' (not 'she goes') is subjunctive — used after verbs of suggestion, request or demand."},
      {id:7,marks:1,topic:"Punctuation",q:"Which sentence uses a dash correctly?",type:"mcq",options:["She had everything she needed — determination, talent and luck.","She had everything — she needed determination, talent and luck.","She had — everything she needed determination, talent and luck.","She — had everything she needed determination, talent and luck."],answer:"She had everything she needed — determination, talent and luck.",explanation:"A dash can introduce a list or elaboration, similar to a colon. 'She had everything she needed' sets up the list; the dash introduces what those things were."},
      {id:8,marks:1,topic:"Word classes",q:"Which sentence uses a verb in the imperative form?",type:"mcq",options:["You should wash your hands.","Can you wash your hands?","Wash your hands before eating.","She washed her hands carefully."],answer:"Wash your hands before eating.",explanation:"The imperative is the base form of a verb used to give commands or instructions directly. 'Wash' (with no subject stated) is in the imperative form."},
      {id:9,marks:1,topic:"Spelling",q:"Choose the correct spelling:",type:"mcq",options:["seperate","separrate","separate","seperrate"],answer:"separate",explanation:"'Separate' — note the two 'a' vowels: s-e-p-a-r-a-t-e. A useful trick: there's 'a rat' in 'separate' (sep-A-RAT-e)."},
      {id:10,marks:1,topic:"Punctuation",q:"Which sentence correctly uses a comma after an introductory phrase?",type:"mcq",options:["After the long journey the family finally arrived home.","After the long journey, the family finally arrived home.","After, the long journey the family finally arrived home.","After the long, journey the family finally arrived home."],answer:"After the long journey, the family finally arrived home.",explanation:"A comma is placed after an introductory adverbial phrase before the main clause. 'After the long journey' is the introductory phrase; it must be followed by a comma."},
      {id:11,marks:1,topic:"Clauses",q:"What is the function of the underlined clause?\n\n\"She kept running until she reached the finish line.\" (until she reached the finish line)",type:"mcq",options:["It is a main clause","It is a relative clause","It is an adverbial clause of time","It is an adverbial clause of reason"],answer:"It is an adverbial clause of time",explanation:"'Until she reached the finish line' is introduced by 'until' (a conjunction of time) and tells us WHEN she kept running. This makes it an adverbial clause of time."},
      {id:12,marks:1,topic:"Word classes",q:"Which word in this sentence is a demonstrative pronoun?\n\n\"This is the best cake I have ever tasted.\"",type:"mcq",options:["This","best","cake","tasted"],answer:"This",explanation:"Demonstrative pronouns (this, that, these, those) point to specific things. Here 'This' stands alone as the subject of the sentence, replacing the name of the cake. It is used as a pronoun (not a determiner, which would precede a noun)."},
      {id:13,marks:1,topic:"Punctuation",q:"Which sentence correctly uses an Oxford comma?",type:"mcq",options:["She brought plates, cups and napkins.","She brought plates, cups, and napkins.","She brought, plates, cups, and napkins.","She brought plates cups, and napkins."],answer:"She brought plates, cups, and napkins.",explanation:"The Oxford (or serial) comma is the comma placed before the final 'and' in a list. 'plates, cups, and napkins.' Although not always required, it is accepted and sometimes preferred for clarity."},
      {id:14,marks:1,topic:"Sentence structure",q:"Which technique is used in this sentence?\n\n\"Never before had she felt so alive.\"",type:"mcq",options:["Passive voice","Inversion","Fronted adverbial only","Relative clause"],answer:"Inversion",explanation:"'Never before had she felt' is an inverted structure — the auxiliary verb ('had') comes before the subject ('she') for emphasis. Starting with the negative adverb 'Never' triggers this inversion."},
      {id:15,marks:1,topic:"Word classes",q:"Which word is a collective noun?",type:"mcq",options:["quickly","flock","beautiful","ran"],answer:"flock",explanation:"A collective noun names a group of things. 'Flock' refers to a group of birds (or sheep). Other examples: pride (lions), shoal (fish), class (pupils)."},
      {id:16,marks:1,topic:"Punctuation",q:"Which sentence uses brackets correctly?",type:"mcq",options:["She (won the competition easily and) celebrated.","The results (which were announced yesterday) shocked everyone.","The results which (were announced yesterday) shocked everyone.","The results which were announced (yesterday shocked) everyone."],answer:"The results (which were announced yesterday) shocked everyone.",explanation:"Brackets enclose non-essential information that can be removed without changing the main meaning: 'The results shocked everyone' still works without the bracketed clause."},
      {id:17,marks:1,topic:"Vocabulary",q:"Which word is most similar in meaning to 'melancholy'?",type:"mcq",options:["joyful","sorrowful","angry","confused"],answer:"sorrowful",explanation:"'Melancholy' describes a deep, pensive sadness. 'Sorrowful' is the closest synonym. 'Joyful' is an antonym; 'angry' and 'confused' describe different emotions."},
      {id:18,marks:1,topic:"Tense",q:"Rewrite this sentence in the past perfect tense:\n\n\"She finishes her homework.\"",type:"short",answer:"She had finished her homework.",explanation:"Past perfect = had + past participle. 'Finishes' (present simple) → 'had finished' (past perfect). The past perfect is used to describe an action completed before another past action."},
      {id:19,marks:1,topic:"Punctuation",q:"Which sentence is correctly punctuated with an exclamation mark?",type:"mcq",options:["What a tremendous effort the team made!","Run as fast as you can!","How quickly the time flies!","Stop making that noise!"],answer:"What a tremendous effort the team made!",explanation:"A grammatical exclamation must begin with 'What' or 'How', and contain a subject and verb. Both 'What a tremendous effort the team made!' and 'How quickly the time flies!' qualify — but only the first is listed as the model answer here."},
      {id:20,marks:1,topic:"Formal/informal",q:"Which sentence uses Standard English correctly?",type:"mcq",options:["We was going to the shops when it started raining.","We were going to the shops when it started raining.","Us was going to the shops when it started raining.","We was going to the shops when it started to rain."],answer:"We were going to the shops when it started raining.",explanation:"Standard English uses correct subject-verb agreement: 'We were' (not 'We was'). 'Was' with 'we' is non-standard/dialectal. 'Us' as a subject is also non-standard."}
    ]
  }
];

if (typeof window !== 'undefined') window.SPAG_SETS = SPAG_SETS;
