// SATBot — Reading Question Sets (multiple years)
// Original texts and questions in the style of KS2 SATs Reading papers

const READING_SETS = [
  {
    year: "2024",
    texts: [
      {
        id: 1, label: "Text 1 — Fiction",
        title: "The Glass Lighthouse",
        body: `The lighthouse had not worked for thirty years.\n\nElla had passed it every day on her walk to school, never giving it a second glance. It stood at the end of the harbour wall like a forgotten exclamation mark — tall, white, and completely useless. The light at its top had been dark since before she was born.\n\nThat changed on the night of the storm.\n\nThe wind had come from the north, sudden and savage, bending the trees along the seafront into trembling arcs. Rain lashed the windows of Ella's bedroom, and she lay awake listening to the harbour bell clang and clang in the gale. It was past midnight when she saw it: a faint, rhythmic pulse of light from the top of the lighthouse. On. Off. On. Off.\n\nShe pressed her face to the cold glass. The light was unmistakable — steady and purposeful against the chaos of the storm.\n\nWithout stopping to think, she pulled on her coat over her pyjamas, shoved her feet into wellington boots, and ran.\n\nThe harbour wall was slick with rain and the wind pushed at her like a living thing. She reached the base of the lighthouse and hammered on the iron door. For a long moment, nothing. Then a sound — a slow, deliberate scraping — and the door opened.\n\nAn old man stood in the doorway, wrapped in a fisherman's jumper, holding a small electric lantern. His face was deeply lined, his white hair wild from the wind.\n\n"Who are you?" Ella demanded.\n\n"Who am I?" he repeated, as though the question amused him. "I used to keep this light. Forty years I kept it burning." He glanced up through the tower window. "Old habits," he said quietly, "die very hard."`
      },
      {
        id: 2, label: "Text 2 — Non-fiction",
        title: "Lighthouses: Guardians of the Coast",
        body: `Before the age of GPS and satellite navigation, the coastlines of Britain were treacherous for sailors. Rocky outcrops lurked just below the surface; sandbanks shifted with the tides; sea mists could swallow an entire fleet. For centuries, lighthouse keepers were among the most important — and isolated — workers in the country.\n\nThe first lighthouses were simply fires lit on clifftops or in iron baskets called 'chauffer' — from the French word for 'stoker'. The Romans built a lighthouse at Dover, the remains of which still stand today. However, it was not until the seventeenth and eighteenth centuries that purpose-built stone lighthouses began to appear on Britain's most dangerous headlands.\n\nThe job of a lighthouse keeper was relentless. The light — originally fuelled by oil, later by gas and electricity — had to be burning from dusk to dawn, every single night of the year, in all weathers. The keeper maintained the lamp mechanism, polished the enormous lens (called a Fresnel lens), wound the clockwork that rotated the beam, and logged every ship that passed.\n\nIsolation was a constant companion. Many lighthouses stood on remote rocks miles from the mainland, accessible only by boat in calm weather. Keepers could spend weeks or months without setting foot on shore. Letters from family arrived irregularly; fresh food was a luxury.\n\nThe last lighthouse in Britain to be automated was North Foreland in Kent, in 1998. Today, no lighthouse in the UK has a resident keeper. The lights still burn — but they are controlled remotely, their rhythmic flashes watched over by computers rather than human eyes.\n\nSomething, many would argue, has been lost.`
      }
    ],
    questions: [
      {id:1,text:1,mark:1,type:"short",q:"From the first two paragraphs, what has Ella's attitude to the lighthouse been up until now?",answer:"She has ignored it / never given it a second glance / not noticed it",explanation:"The text says she had 'never giving it a second glance' — she walked past it daily without interest or attention."},
      {id:2,text:1,mark:1,type:"short",q:"Find and copy the simile used to describe the lighthouse in the second paragraph.",answer:"like a forgotten exclamation mark",explanation:"The simile compares the lighthouse to 'a forgotten exclamation mark' — it is tall, stands upright, and is neglected, like old punctuation nobody uses."},
      {id:3,text:1,mark:2,type:"long",q:"How does the writer create a sense of danger during the storm? Give two examples from the text.",answer:"The wind came sudden and savage / trees bent into trembling arcs / rain lashed windows / harbour bell clanged / harbour wall was slick / wind pushed at her like a living thing",explanation:"Examples include: 'sudden and savage' (violent adjectives); 'bending the trees...into trembling arcs' (personification/image); 'harbour wall was slick with rain'; 'the wind pushed at her like a living thing' (simile). Any two with brief explanation."},
      {id:4,text:1,mark:1,type:"short",q:"What did Ella see that made her leave the house in the middle of the night?",answer:"A faint rhythmic pulse of light from the lighthouse / the lighthouse light flashing on and off",explanation:"She saw 'a faint, rhythmic pulse of light from the top of the lighthouse. On. Off. On. Off.' — which she knew had been dark for years."},
      {id:5,text:1,mark:2,type:"long",q:"What do the old man's final words tell you about his character? Use evidence from the text.",answer:"He is dedicated / loyal / unable to let go of the past / the phrase 'old habits die very hard' suggests his identity is tied to keeping the light",explanation:"'Old habits die very hard' and 'Forty years I kept it burning' show he is deeply committed to his role — even after thirty years, he still feels compelled to light the tower. He acts from duty and memory rather than necessity."},
      {id:6,text:1,mark:1,type:"short",q:"Find and copy a phrase that shows the man had worked as a lighthouse keeper for a long time.",answer:"Forty years I kept it burning",explanation:"'Forty years I kept it burning' directly states the length of his service — a very long time spent tending the light."},
      {id:7,text:1,mark:1,type:"short",q:"How is the man described when he opens the door? Give two details.",answer:"Deeply lined face / white hair wild from the wind / wrapped in a fisherman's jumper / holding a small electric lantern",explanation:"The text describes: 'His face was deeply lined, his white hair wild from the wind' — two physical details that suggest age and exposure to the elements."},
      {id:8,text:2,mark:1,type:"short",q:"According to the text, what were 'chauffers'?",answer:"Iron baskets used to hold fires / early lighthouses made of fire in iron baskets",explanation:"The text explains: 'fires lit on clifftops or in iron baskets called 'chauffer' — from the French word for stoker.'"},
      {id:9,text:2,mark:1,type:"short",q:"Name two tasks a lighthouse keeper had to carry out.",answer:"Maintain the lamp / polish the Fresnel lens / wind the clockwork / log passing ships / keep the light burning",explanation:"The text lists: maintaining the lamp, polishing the Fresnel lens, winding the clockwork that rotated the beam, and logging every ship that passed. Any two are acceptable."},
      {id:10,text:2,mark:2,type:"long",q:"How does the text show that isolation was a serious challenge for lighthouse keepers?",answer:"Lighthouses on remote rocks miles from mainland / accessible only by boat in calm weather / weeks or months without going ashore / letters arrived irregularly / fresh food was a luxury",explanation:"The text uses several specific details: location on 'remote rocks miles from the mainland', only accessible 'in calm weather', spending 'weeks or months without setting foot on shore', irregular letters, and scarce fresh food. These combine to paint a picture of extreme isolation."},
      {id:11,text:2,mark:1,type:"short",q:"When was the last British lighthouse to be automated, and where was it?",answer:"1998 / North Foreland in Kent",explanation:"'The last lighthouse in Britain to be automated was North Foreland in Kent, in 1998.'"},
      {id:12,text:2,mark:2,type:"long",q:"What is the effect of the final sentence, 'Something, many would argue, has been lost'? What has been lost?",answer:"Suggests regret / loss of human presence and connection / keepers' dedication, knowledge and sense of duty has gone / technology replaced a human tradition",explanation:"The final sentence is deliberately vague — 'something' rather than naming it. This invites the reader to reflect. What is lost is the human element: the keeper's dedication, their connection to sailors, the personal responsibility. Automation makes the light more efficient but removes the human story."},
      {id:13,text:2,mark:1,type:"short",q:"What did the Fresnel lens do?",answer:"It was the large lens used in the lighthouse lamp",explanation:"The text calls it 'the enormous lens (called a Fresnel lens)' — it was part of the lamp mechanism that the keeper polished. Its purpose was to focus and amplify the beam of light."},
      {id:14,text:2,mark:1,type:"short",q:"According to the text, what fuels have been used in lighthouse lamps over time?",answer:"Oil, gas, electricity",explanation:"'The light — originally fuelled by oil, later by gas and electricity.'"},
      {id:15,text:0,mark:3,type:"long",q:"Both texts deal with the idea of dedication to keeping the lighthouse light burning. How does each text show this? Use evidence from both texts in your answer.",answer:"Fiction: old man kept light for 40 years / lit it again from habit and duty / 'old habits die very hard' / Non-fiction: keepers worked every night all year / extreme isolation / last human keeper only left in 1998",explanation:"Text 1 shows dedication through the old man's character — he worked for forty years and still instinctively lights the tower during a storm. 'Old habits die very hard' captures lifelong commitment. Text 2 shows dedication through facts: keepers worked every single night 'in all weathers', endured months of isolation, and the human tradition continued until 1998. Together the texts show dedication as both personal (Text 1) and professional/historical (Text 2)."}
    ]
  },
  {
    year: "2023",
    texts: [
      {
        id: 1, label: "Text 1 — Fiction",
        title: "The Last Forest",
        body: `Nobody went to the old forest any more.\n\nThe village children had been told it was dangerous — old trees fell without warning, the paths were unreliable, and the light barely reached the ground even in summer. These were sensible reasons, Asha supposed. But she also suspected there was something else: the forest made people uncomfortable in a way they couldn't easily explain.\n\nShe had felt it herself, the first time she stepped between the trees. A stillness so deep it seemed almost solid. A sense that the air was older somehow, denser, as though it had been breathed by a thousand years of living things.\n\nShe went back, of course.\n\nEach visit she went a little further. She learned to read the forest floor — which mosses meant water nearby, which fungus grew only on dying oak, which hollows might shelter a fox in winter. She began to feel less like an intruder and more like a regular visitor to a place that had its own unspoken rules.\n\nThen one October morning she found the tree.\n\nIt stood at the centre of a small clearing, broader than any tree she had seen, its bark grey and deeply furrowed like the face of a very old person. A thick root arched above the ground like a gateway, and beneath it — tucked into the dark hollow — was a small tin box.\n\nInside the tin box were photographs. Dozens of them, black and white, of children she didn't know standing in front of this same tree. The dates written on the backs stretched back over a hundred years.\n\nShe sat with them a long time, the forest perfectly quiet around her.`
      },
      {
        id: 2, label: "Text 2 — Non-fiction",
        title: "Ancient Woodland: Why It Matters",
        body: `Ancient woodland is defined as land that has been continuously wooded since at least 1600 AD in England and Wales. These forests — some far older than any living person can remember — are among the most biodiverse habitats on Earth.\n\nUnlike modern plantations, which are planted for timber and typically contain just one or two species of tree, ancient woodland has had centuries to develop complex layers of life. A single hectare may contain hundreds of species of plants, insects, fungi, birds and mammals, many of which are found nowhere else.\n\nThe trees themselves are remarkable. Ancient oaks, for example, support more species of insect than any other native British tree — over 280 different species depend on them at various stages of their life cycle. A veteran oak that has stood for 500 years may have hollow cavities used by owls, bats and beetles; its fallen branches provide habitat for another community of species entirely.\n\nOne of the most important — and least visible — elements of ancient woodland is the mycorrhizal network: a vast web of fungi that grows through the soil, connecting the roots of different trees. Scientists have discovered that trees use this network to transfer nutrients and even chemical signals to one another. A tree under attack from insects, for example, can signal to its neighbours to produce defensive chemicals.\n\nDespite their importance, ancient woods cover only 2.5% of the UK's land area. Almost half of the ancient woodland that existed in 1930 has since been destroyed — cleared for farmland, housing or roads.\n\nWhat takes centuries to build can be lost in an afternoon.`
      }
    ],
    questions: [
      {id:1,text:1,mark:1,type:"short",q:"Why do the village children avoid the old forest?",answer:"They are told it is dangerous — old trees fall, paths are unreliable, light barely reaches the ground",explanation:"The text lists three 'sensible reasons': falling trees, unreliable paths, and lack of light. These are the official reasons the village children have been given."},
      {id:2,text:1,mark:1,type:"short",q:"Find and copy a phrase that describes the unusual atmosphere inside the forest.",answer:"A stillness so deep it seemed almost solid / the air was older somehow, denser",explanation:"Either phrase works: 'A stillness so deep it seemed almost solid' (personifying or solidifying silence) or 'the air was older somehow, denser' (suggesting the air itself has a history)."},
      {id:3,text:1,mark:2,type:"long",q:"How does Asha's relationship with the forest change during her visits? Use evidence from the text.",answer:"She goes further each visit / learns to read the forest floor / feels less like an intruder and more like a regular visitor",explanation:"The text shows a progression: she first enters, then returns, then explores further, then gains knowledge ('learned to read the forest floor'), and finally feels comfortable — 'less like an intruder and more like a regular visitor'."},
      {id:4,text:1,mark:1,type:"short",q:"Find and copy the simile used to describe the bark of the ancient tree.",answer:"its bark grey and deeply furrowed like the face of a very old person",explanation:"The simile compares the tree's bark to 'the face of a very old person' — the deep grooves of bark are like deep wrinkles. This also suggests the tree's great age."},
      {id:5,text:1,mark:2,type:"long",q:"What is the significance of the tin box Asha finds? What does it suggest about the tree's history?",answer:"Many different children visited the same tree over more than 100 years / the tree has been important to people for a long time / photographs show a long tradition of visiting",explanation:"The tin box contains 'dozens' of photographs spanning over a century — it shows the tree has been visited and valued by many generations. It suggests the tree is a place of meaning and continuity, even if the current village has forgotten it."},
      {id:6,text:1,mark:1,type:"short",q:"How does the writer end the story? What effect does this create?",answer:"Asha sits quietly with the photographs / the forest is perfectly quiet / creates a sense of peace and reflection",explanation:"The story ends with Asha sitting in silence with the photographs — 'the forest perfectly quiet around her.' This ending is still and reflective, encouraging the reader to think about what Asha has discovered and its meaning."},
      {id:7,text:1,mark:1,type:"short",q:"What had Asha learned to identify during her forest visits? Give two examples from the text.",answer:"Which mosses meant water nearby / which fungus grew on dying oak / which hollows might shelter a fox in winter",explanation:"The text lists: 'which mosses meant water nearby, which fungus grew only on dying oak, which hollows might shelter a fox in winter.' Any two are correct."},
      {id:8,text:2,mark:1,type:"short",q:"What is the definition of 'ancient woodland' used in the text?",answer:"Land continuously wooded since at least 1600 AD in England and Wales",explanation:"The text opens with: 'Ancient woodland is defined as land that has been continuously wooded since at least 1600 AD in England and Wales.'"},
      {id:9,text:2,mark:1,type:"short",q:"How is ancient woodland different from modern plantations?",answer:"Ancient woodland has complex layers of many species; plantations have only one or two species of tree and are grown for timber",explanation:"The text contrasts 'modern plantations, which are planted for timber and typically contain just one or two species' with ancient woodland which has 'had centuries to develop complex layers of life.'"},
      {id:10,text:2,mark:2,type:"long",q:"Explain what the mycorrhizal network is and why it is important.",answer:"A web of fungi connecting tree roots / allows trees to transfer nutrients and chemical signals / trees can warn neighbours about insect attacks",explanation:"The text explains it as 'a vast web of fungi that grows through the soil, connecting the roots of different trees.' Its importance is that trees use it to 'transfer nutrients and even chemical signals' — even warning each other of insect attacks."},
      {id:11,text:2,mark:1,type:"short",q:"How many species of insect depend on ancient oaks?",answer:"Over 280",explanation:"'Ancient oaks...support more species of insect than any other native British tree — over 280 different species depend on them.'"},
      {id:12,text:2,mark:1,type:"short",q:"How much ancient woodland that existed in 1930 has been destroyed?",answer:"Almost half",explanation:"'Almost half of the ancient woodland that existed in 1930 has since been destroyed.'"},
      {id:13,text:2,mark:2,type:"long",q:"How does the writer of Text 2 make the reader feel that ancient woodland is precious and worth protecting?",answer:"Statistics (280 species, only 2.5% of UK); examples of what is lost (centuries of habitat); final sentence creates urgency",explanation:"The writer uses statistics ('over 280 species', 'only 2.5% of land'), lists all the life that depends on these woods, and ends with a powerful sentence: 'What takes centuries to build can be lost in an afternoon.' This creates a sense of irreplaceable value and urgent loss."},
      {id:14,text:2,mark:1,type:"short",q:"What three things have ancient woodlands been destroyed to make way for?",answer:"Farmland, housing and roads",explanation:"'cleared for farmland, housing or roads' — all three are stated."},
      {id:15,text:0,mark:3,type:"long",q:"Both texts suggest that ancient trees connect us to the past. How do the writers show this? Use evidence from both texts.",answer:"Text 1: photographs over 100 years / same tree visited by generations / tin box preserves memory. Text 2: trees 500+ years old / support species that evolved with them / centuries to develop",explanation:"In Text 1, the photographs spanning over a century show that generations of children have connected with the same tree — it holds the memory of many lives. In Text 2, the writer describes veteran oaks that are 500 years old, supporting hundreds of species that have 'had centuries to develop.' Both texts show trees as living links across time — the fiction through human memory, the non-fiction through ecological history."}
    ]
  },
  {
    year: "2022",
    texts: [
      {
        id: 1, label: "Text 1 — Fiction",
        title: "The Ice Sculptor",
        body: `The sculpture had been there since Friday.\n\nEveryone in the market square had noticed it: a bear, life-sized and astonishingly detailed, carved from a single block of ice. Its paw was raised, its head turned slightly to one side, as though it had just caught a scent on the wind. In the pale winter sun, it glittered so brightly that people stopped mid-step to look at it.\n\nBut no one had seen who made it.\n\nMarcus had watched it change over three days. On Friday, the details had been sharp and astonishing — each claw distinct, the fur textured, the eyes deep and clear. By Sunday the edges had softened, the fine lines blurring into curves. The bear was becoming something else, something more abstract, as though it were returning by degrees to the formless block from which it had come.\n\nOn Monday morning, Marcus arrived at the square before school and found the sculptor.\n\nShe was perhaps sixty, with short grey hair and large capable hands. She stood a few feet from the bear, simply watching it melt. She had a sketchbook open but was not drawing.\n\n"Is it yours?" Marcus asked.\n\n"It was," she said. "Now it belongs to anyone who looks at it."\n\nMarcus stared at the bear. The right paw had rounded completely; the claws were gone. Water ran silently from its base, darkening the cobblestones.\n\n"Doesn't it bother you?" he said. "That it's disappearing?"\n\nShe considered this seriously. "Every sculpture disappears eventually," she said. "Stone erodes. Bronze oxidises. Ice is simply more honest about it." She closed the sketchbook. "The making is the point. Not the keeping."`
      },
      {
        id: 2, label: "Text 2 — Non-fiction",
        title: "The Art of Ice Sculpture",
        body: `Ice sculpture is one of the world's most ancient art forms — and one of the most temporary. Carved from blocks of crystal-clear ice, these works can take skilled artists days to create, yet they may exist for only a matter of hours before they melt away.\n\nThe craft has roots in northern China, where carvings in ice were documented as early as the 17th century. In Japan, ice carving became associated with major festivals, where enormous sculptures — some over five metres tall — were displayed in town squares each winter. Today, international competitions attract artists from around the world to cities such as Harbin in China and Fairbanks in Alaska, where temperatures can drop to −40°C, allowing sculptures to survive for weeks.\n\nModern ice sculptors work with chainsaw, chisels and specialist tools, shaping blocks that can weigh up to 300 kilograms. The clarity of the ice is crucial — air bubbles or impurities create a cloudy appearance that obscures fine detail. For major competitions, specially manufactured 'crystal ice' is used, frozen slowly under controlled conditions to ensure maximum transparency.\n\nIce sculpture requires not just artistic skill but an understanding of the material's unique properties. Ice is brittle; large unsupported sections can crack or break under their own weight. Temperature management is essential — a sculpture left in direct sunlight will deteriorate rapidly, while one kept in the right conditions can remain stable for days.\n\nBut perhaps the most striking characteristic of ice sculpture is its impermanence. Unlike stone or bronze, ice returns to water. Artists who choose this medium do so knowing that their work will disappear — and many argue that this is precisely what gives ice sculpture its power. The beauty is inseparable from the transience.`
      }
    ],
    questions: [
      {id:1,text:1,mark:1,type:"short",q:"What was unusual about the ice sculpture in the market square?",answer:"Nobody had seen who made it / it appeared without anyone seeing the sculptor",explanation:"The text says 'no one had seen who made it' — despite being in a busy market square, the sculptor and the making of it remained a mystery."},
      {id:2,text:1,mark:1,type:"short",q:"Find and copy a phrase from the third paragraph that shows how the sculpture was changing over the three days.",answer:"The edges had softened / the fine lines blurring into curves / becoming something more abstract",explanation:"'The edges had softened, the fine lines blurring into curves' — the precise detail of the sculpture was gradually disappearing as it melted."},
      {id:3,text:1,mark:2,type:"long",q:"How does the writer make the ice bear sound impressive when it was first made? Give two examples.",answer:"Life-sized / astonishingly detailed / single block of ice / each claw distinct / fur textured / eyes deep and clear / glittered so brightly people stopped mid-step",explanation:"Examples: 'astonishingly detailed', 'each claw distinct, the fur textured, the eyes deep and clear' — specific physical details; 'glittered so brightly that people stopped mid-step' — the effect on passers-by. Any two with brief explanation."},
      {id:4,text:1,mark:1,type:"short",q:"What was the sculptor doing when Marcus found her?",answer:"Watching the bear melt / standing near it with a sketchbook open but not drawing",explanation:"She 'stood a few feet from the bear, simply watching it melt. She had a sketchbook open but was not drawing.' She was observing, not recording."},
      {id:5,text:1,mark:2,type:"long",q:"What does the sculptor's response to Marcus reveal about her attitude to her work? Use evidence.",answer:"She is philosophical about impermanence / doesn't mind the bear melting / values the process of making more than the finished piece / 'the making is the point. Not the keeping.'",explanation:"Her final words — 'The making is the point. Not the keeping.' — reveal she values creation over preservation. She also compares ice to other materials: 'Ice is simply more honest about it', suggesting she accepts and even respects impermanence."},
      {id:6,text:1,mark:1,type:"short",q:"Find and copy the metaphor used to describe the bear returning to its original state.",answer:"returning by degrees to the formless block from which it had come",explanation:"This is a metaphor — the melting sculpture is compared to 'returning' to what it was before it was carved. The bear was made from ice; it is becoming ice again."},
      {id:7,text:1,mark:1,type:"short",q:"How does the writer show that the sculpture was melting by Monday morning?",answer:"The right paw had rounded completely / the claws were gone / water ran silently from its base, darkening the cobblestones",explanation:"Two details: 'The right paw had rounded completely; the claws were gone' and 'Water ran silently from its base, darkening the cobblestones' — both show the physical reality of the melting."},
      {id:8,text:2,mark:1,type:"short",q:"Where did ice carving first originate, according to the text?",answer:"Northern China",explanation:"'The craft has roots in northern China, where carvings in ice were documented as early as the 17th century.'"},
      {id:9,text:2,mark:1,type:"short",q:"What tools do modern ice sculptors use?",answer:"Chainsaw, chisels and specialist tools",explanation:"'Modern ice sculptors work with chainsaw, chisels and specialist tools.'"},
      {id:10,text:2,mark:2,type:"long",q:"Why is the clarity of the ice so important, and what is done to ensure it?",answer:"Cloudy ice from air bubbles obscures fine detail / 'crystal ice' is specially manufactured, frozen slowly under controlled conditions for maximum transparency",explanation:"The text explains: 'air bubbles or impurities create a cloudy appearance that obscures fine detail.' To prevent this, major competitions use 'specially manufactured crystal ice, frozen slowly under controlled conditions to ensure maximum transparency.'"},
      {id:11,text:2,mark:1,type:"short",q:"Name two cities mentioned in the text that hold international ice sculpture competitions.",answer:"Harbin (China) and Fairbanks (Alaska)",explanation:"'cities such as Harbin in China and Fairbanks in Alaska' — both hold major competitions where low temperatures allow sculptures to survive for weeks."},
      {id:12,text:2,mark:2,type:"long",q:"According to the text, what makes ice a challenging material to work with?",answer:"It is brittle / large sections can crack under their own weight / temperature must be managed / direct sunlight causes rapid deterioration",explanation:"The text lists multiple challenges: 'Ice is brittle; large unsupported sections can crack or break under their own weight.' Also 'temperature management is essential — a sculpture left in direct sunlight will deteriorate rapidly.'"},
      {id:13,text:2,mark:1,type:"short",q:"What does the writer mean by 'The beauty is inseparable from the transience'?",answer:"The beauty of ice sculpture comes from / is connected to the fact that it will not last",explanation:"'Transience' means not lasting long. The writer argues that part of what makes ice sculptures beautiful is precisely that they are temporary — the fragility and impermanence are part of the art form's appeal."},
      {id:14,text:2,mark:1,type:"short",q:"How heavy can ice blocks used in sculpture be?",answer:"Up to 300 kilograms",explanation:"'shaping blocks that can weigh up to 300 kilograms.'"},
      {id:15,text:0,mark:3,type:"long",q:"Both texts explore the idea that the impermanence of ice sculpture is part of its value. How is this shown in each text? Use evidence from both texts.",answer:"Text 1: sculptor says 'the making is the point, not the keeping' / ice is 'more honest' about impermanence than stone or bronze. Text 2: artists choose the medium knowing it will disappear / 'beauty is inseparable from the transience'",explanation:"In Text 1, the sculptor actively embraces impermanence — she watches her work melt without distress and argues that 'the making is the point.' She values creation over preservation. In Text 2, the writer explains that artists 'do so knowing that their work will disappear — and many argue that this is precisely what gives ice sculpture its power.' Both texts agree that impermanence is not a flaw but a feature — it is what makes the art meaningful."}
    ]
  }
];

if (typeof window !== 'undefined') window.READING_SETS = READING_SETS;
